<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>apply score rate</name>
  <uuid>15423ca4-e241-4f0e-9c04-48774732b46f</uuid>
  <documentation><![CDATA[Calculates the fees for the services based on the services and score rate. The result is rounded to output as integer.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[
	set decision to round( decision * 'Score rate' , 0 ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
