<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>create scoreboard</name>
  <uuid>c3f35774-d818-4337-a031-b8e89b5d5a80</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Scoreboard where
        the Confidence is round( the Confidence of 'Predictive risk' * 100 , 4 ) , 
        High risk is 'Predictive risk' is High risk ,
        the Segment is 'Segment category' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
