<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>compute services count</name>
  <uuid>7363ce05-1666-4ac4-8a98-3ab3dd9c3f0c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Score rate' is more than 1
then
	set decision to 1 ;
else
    set decision to 2 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
