<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-rule</name>
  <uuid>67ba705b-a1c1-44e5-a838-2c08597ba68a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new ML model output where
		the confidence is 0 , 
		the weight is 0 , 
		the rank is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
