<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set industry input</name>
  <uuid>ed9e4fa0-8514-42b7-ab72-5e1a2b6821ef</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the clientindustry is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
