<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set extended services</name>
  <uuid>eec47a82-1da0-4fec-b2b9-be4469aca9a1</uuid>
  <documentation><![CDATA[Builds the list of services and fees.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Service Information where
		the Extended services are 'Additional services' , 
		the Services Fee is Fee ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
